### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by bobhenl** [ExyronProvider/FastCrystalsPlugin#12]

**Comment by bobhenl** [comment]
```
[16:24:42] [Server thread/ERROR]: Error occurred while enabling Exyron-FastCrystals v1.0 (Is it up to date?)
java.lang.IllegalStateException: Plugin is disabling due to unsupported minecraft version (1.21). We currently support only 1.16.4+ versions.
	at FastCrystalsPlugin-1.0.jar/xyz.exyron.fastcrystals.FastCrystalsPlugin.assignCrystalDamageFromServerVersion(FastCrystalsPlugin.java:100) ~[FastCrystalsPlugin-1.0.jar:?]
	at FastCrystalsPlugin-1.0.jar/xyz.exyron.fastcrystals.FastCrystalsPlugin.onEnable(FastCrystalsPlugin.java:42) ~[FastCrystalsPlugin-1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:756) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:518) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2274-c3849be]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by bobhenl** [comment]
Anything new?
