### ISSUE TITLE
error msg in 1.19.4

### ISSUE THREAD

**Issue by adalmo** [ExyronProvider/FastCrystalsPlugin#5]
[12:55:17 ERROR]: Could not pass event EntityDamageByEntityEvent to Exyron-FastCrystals v1.0
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R2/entity/CraftPlayer
        at xyz.exyron.fastcrystals.FastCrystalsPlugin.onEntityDamageByEntity(FastCrystalsPlugin.java:55) ~[fast-crystals-plugin-1.19.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor240.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1946]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:249) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1168) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1025) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callNonLivingEntityDamageEvent(CraftEventFactory.java:1221) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1225) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1211) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.world.entity.boss.enderdragon.EntityEnderCrystal.a(EntityEnderCrystal.java:187) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1353) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2221) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.network.PlayerConnection$6.a(PlayerConnection.java:2952) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2874) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1368) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1345) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1338) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1316) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1204) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer
        ... 37 more

**Comment by FastNinjax** [comment]
this is a spigot plugin ur using pupur it wont work

**Comment by adalmo** [comment]
but somehow it was worked on 1.19.3 purpur but ok then

**Comment by adalmo** [comment]
ok it got updated to 1.19.4 so i ma close this
