### ISSUE TITLE
On new update 1.20.2 getting following error for players

### ISSUE THREAD

**Issue by etvgaming** [ExyronProvider/FastCrystalsPlugin#6]
On new update 1.20.2 getting following error for players

[14:35:12 ERROR]: Could not pass event EntityDamageByEntityEvent to Exyron-FastCrystals v1.0
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R2/entity/CraftPlayer
at xyz.exyron.fastcrystals.FastCrystalsPlugin.onEntityDamageByEntity(FastCrystalsPlugin.java:55) ~[fast-crystals-plugin-1.20.2.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor328.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:git-Pufferfish-26]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264) ~[puffer

**Comment by KamlaXPL** [comment]
You are using 1.20.1 version, not 1.20.2, try previous version :)
